# Generated by Django 4.0.5 on 2022-07-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userDetails',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=30)),
                ('userName', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('SCOST', models.PositiveIntegerField()),
                ('DCOST', models.PositiveIntegerField()),
                ('SOLD', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('userEmail', models.CharField(max_length=30)),
                ('userPassword', models.CharField(max_length=30)),
                ('isAdmin', models.BooleanField()),
                ('Mobile', models.BigIntegerField()),
            ],
        ),
    ]
